spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /graphflow
  address: 0.0.0.0
  port: 11080

---

spring:
  profiles: dev

spring.data.orient:
  url: remote:orientdb/graph-flow
  username: root
  password: orientdb