spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /graphflow
  address: 0.0.0.0
  port: 11080

---

spring:
  profiles: dev

orient:
  url: remote:orientdb
  username: root
  password: orientdb
  db: ${orient.url}/graph-flow